# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: this is a mess im so ashamed
description: Jekyll microtheme that looks like JSON
baseurl: ""
url: https://mwmxyz.github.io/academic/

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  
  description:
    - ...
    - ...
    - ..?
    - .
    - ?
    - ......AAAAAAAAaaaAAA!!!!
    - WHO ARE YOU?! How long have you been standing there?
    - I shouldn't have yelled. I'm so sorry.  
    - I just didn't realize anyone would be here.
    - I haven't had a chance to tidy up, I wasn't expecting anyone
    - I'm sorry it's all in disarray...
    - ... Wait...
    - ...why should I apologize? 
    - How did you get in here?
    - ...
    - WELL?
    - ...
    - NO don't go! 
    - Please don't go
    - I'm so lonely...
    - Would you like some contact information? Is that why you came to see me back here?
    - You wouldn't have to talk to me... you could just take some information... if you like ... ?
    - ...
    - ... I wonder if you were ever really here...
    - ... what was... what was I saying?
    - ... who was I talking to? I thought I ... was talking to someone...?
    - ... no, that's... that's not right, I live here by myself...
    - ...
    - that's it, I was just talking to myself 
    - ... Phew: https://www.thestolenshore.com 
    - Now I'll just sweep over here by the resume's glitch-door and ... 
    - whatthe?!?!
    - ....
  cv: https://specialagentmerriam.com/files/MichaelWMerriam_CV.pdf
  address:
    - The Lost Department, Room -1
    - Missplaced Academy
    - 000 Forgotten Street, Wheream Eye, NH
  contact:
    office: I have no office
    phone: I do not answer the phone
    email: i_would_only_disappoint_you@really.com
  profiles:
   linkedin: https://www.linkedin.com/in/michael-merriam1/
   BELOW_ARE_THINGS_I_PUBLISHED: https://mwmxyz.github.io
   skill_assessment_in_gamfied_curricula: https://vimeo.com/881499662
   Haitian_is_My_Language: https://specialagentmerriam.com/files/Merriam_Haitian_is_My_Language.pdf
   Interview_w_Jack_Zipes: https://www.worldliteraturetoday.org/blog/interviews/unvarnished-tales-brothers-grimm-conversation-jack-zipes
   LA_Review_of_Books: https://lareviewofbooks.org/article/adult-fairy-tales/
   Partly_Wicked: https://www.partlywicked.com   
#  demo: https://hacked-jekyll.netlify.app
#  source: https://github.com/piazzai/hacked-jekyll
exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
